add code to install manpages

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -7,6 +7,8 @@ export ZOPEN_GIT_URL="https://github.com/git/git"
 export ZOPEN_GIT_DEPS="curl git make m4 perl autoconf automake help2man texinfo xz zlib openssl expat gettext coreutils diffutils bash"
 
 export ZOPEN_TARBALL_URL="https://www.kernel.org/pub/software/scm/git/git-2.39.1.tar.xz"
+export ZOPEN_TARBALL_MAN_REL="2.9.5"
+export ZOPEN_TARBALL_MAN_URL="https://mirrors.edge.kernel.org/pub/software/scm/git/git-manpages-${ZOPEN_TARBALL_MAN_REL}.tar.xz"
 export ZOPEN_TARBALL_DEPS="curl git make m4 perl autoconf automake help2man texinfo xz zlib openssl expat gettext gzip tar coreutils zoslib diffutils ncurses bash sed"
 
 export ZOPEN_RUNTIME_DEPS="perl bash less ncurses" # If building with shared libs, add openssl, curl
@@ -63,7 +65,7 @@ zopen_install_all()
     return 4;
   fi
 }
-# Run an 'zopen_pre_check' routine to clean out any GIT environment variables 
+# Run a 'zopen_pre_check' routine to clean out any GIT environment variables 
 # that might interfere with a new GIT operation during the test run
 #
 zopen_pre_check()
@@ -120,7 +122,40 @@ EOF
 zopen_post_install()
 {
   # Install a cacert.pem to be used (optionally) by the customer
-  zopen update-cacert -f $1
+  if ! zopen update-cacert -f $1 ; then
+    return 4
+  fi
+
+  # Install man pages from ${GIT_MANPAGES_URL}
+  if [ "${ZOPEN_TYPE}" = "TARBALL" ]; then
+    GIT_SRC_DIR="${PWD}"
+    GIT_ROOT="${GIT_SRC_DIR}/.."
+    GIT_MAN_REL_DIR="git-manpages"
+    GIT_MAN_DIR="${GIT_ROOT}/${GIT_MAN_REL_DIR}"
+    GIT_MAN_TARBALL="${GIT_ROOT}/${GIT_MAN_REL_DIR}.tar.xz"
+
+    if ! [ -d "${GIT_MAN_TARBALL}" ]; then 
+      if ! curl -L "${ZOPEN_TARBALL_MAN_URL}" -o "${GIT_MAN_TARBALL}" ; then
+        echo "Unable to download ${GIT_MAN_TARBALL} from ${ZOPEN_TARBALL_MAN_URL}" >&2
+        return 4
+      fi
+    fi
+    if ! rm -rf  "${GIT_MAN_DIR}"  || ! mkdir "${GIT_MAN_DIR}" || ! tar -C "${GIT_MAN_DIR}" -axf "${GIT_MAN_TARBALL}" ; then
+      echo "Unable to untar and create directory ${GIT_MAN_DIR}" >&2
+      return 4
+    fi
+    if (! cd "${GIT_MAN_DIR}" || ! git init || ! git checkout -b master || ! git add . || ! git commit -m 'base' ) ; then
+      echo "Unable to set up local git repo for ${GIT_MAN_DIR}" >&2
+      return 4
+    fi
+    if ! make quick-install-man ; then
+      echo "Unable to install git man pages" >&2
+      return 4
+    fi
+  else
+    echo "Add code for GIT build of manpages" >&2
+    return 4
+  fi
 }
 
 zopen_get_version() {
